In [1]:
import numpy as np 
import pandas as pd

In [2]:
train = pd.read_csv('stock_train.csv')
test = pd.read_csv('stock_test.csv')

In [3]:
train

,Date,Close
0,2024-01-02,10000.00
1,2024-01-03,10024.38
2,2024-01-04,9940.98
3,2024-01-05,10014.32
4,2024-01-06,9883.17
...,...,...
298,2024-10-26,20598.10
299,2024-10-27,20424.36
300,2024-10-28,20786.96
301,2024-10-29,20753.59


In [4]:
train['r'] = train['Close'].diff(1)/train['Close'].shift(1)

In [5]:
train

,Date,Close,r
0,2024-01-02,10000.00,NaN
1,2024-01-03,10024.38,0.002438
2,2024-01-04,9940.98,-0.008320
3,2024-01-05,10014.32,0.007378
4,2024-01-06,9883.17,-0.013096
...,...,...,...
298,2024-10-26,20598.10,-0.004882
299,2024-10-27,20424.36,-0.008435
300,2024-10-28,20786.96,0.017753
301,2024-10-29,20753.59,-0.001605


In [6]:
A = np.zeros((train.shape[0] - 3, 6))

In [7]:
r = train["Close"].pct_change().to_numpy()

In [8]:
b = train['r'].to_numpy()[3:]

In [9]:
for i, t in enumerate(range(3, len(r))):
      lag1, lag2 = r[t - 1], r[t - 2]
      if lag1 >= 0:
          A[i, :3] = [1, lag1, lag2]
      else:
          A[i, 3:] = [1, lag1, lag2]

In [10]:
A

array([[ 0.        ,  0.        ,  0.        ,  1.        , -0.00831972,
         0.002438  ],
       [ 1.        ,  0.00737754, -0.00831972,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.01309625,
         0.00737754],
       ...,
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.00843476,
        -0.00488232],
       [ 1.        ,  0.01775331, -0.00843476,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.00160533,
         0.01775331]])

In [11]:
b

array([ 7.37754225e-03, -1.30962462e-02,  3.58285854e-03,  9.51749142e-04,
        9.13072294e-03,  4.40677256e-03,  7.25442769e-03,  6.70493359e-03,
        1.09283030e-02,  3.42404334e-03,  1.32291720e-02,  1.72299700e-03,
        7.51217683e-03,  6.85245353e-03,  2.10977512e-02,  3.36154532e-03,
        9.37767894e-03,  3.26925188e-03, -3.34090025e-03,  5.78495748e-03,
       -6.75766508e-03, -4.58541841e-03,  1.64714879e-03,  8.42445324e-03,
       -4.35700186e-02,  1.67003886e-02, -1.23938763e-03, -6.57485926e-03,
        1.29942244e-02,  1.18366113e-02,  3.07961316e-03,  8.14397958e-03,
        1.01903371e-02,  1.16346557e-03,  1.27912876e-03, -7.12970496e-03,
        5.05232930e-03,  7.57392218e-03,  5.16659909e-03,  1.07426271e-03,
       -3.00946929e-03, -3.20516789e-03,  4.00780799e-03,  2.28179153e-03,
        6.04329766e-03,  2.45047559e-03,  2.07991089e-03, -9.31181719e-03,
       -6.28883184e-03, -5.89171579e-03,  1.14761669e-02,  9.67927593e-03,
        3.42449311e-03,  

In [12]:
A.shape, b.shape

((300, 6), (300,))

In [13]:
b[:5]

array([ 0.00737754, -0.01309625,  0.00358286,  0.00095175,  0.00913072])

## Penyelesaian via Persamaan Normal

In [14]:
A_normal = A.T @ A
b_normal = A.T @ b

In [15]:
A_normal

array([[ 1.95000000e+02,  1.44561911e+00,  6.24790298e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.44561911e+00,  1.68323857e-02,  2.82513509e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.24790298e-01,  2.82513509e-03,  1.91107639e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.05000000e+02, -7.04398054e-01,  1.20474096e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.04398054e-01,  1.01917668e-02, -8.19610043e-05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.20474096e-01, -8.19610043e-05,  7.91675532e-03]])

In [16]:
b_normal

array([ 0.6477362 ,  0.00555468,  0.00460568,  0.11328741, -0.00280966,
       -0.00098588])

In [17]:
A_normal.shape, b_normal.shape

((6, 6), (6,))

In [18]:
normal_system = np.concatenate((A_normal, b_normal.reshape(-1, 1)), axis=1)

In [19]:
normal_system

array([[ 1.95000000e+02,  1.44561911e+00,  6.24790298e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         6.47736199e-01],
       [ 1.44561911e+00,  1.68323857e-02,  2.82513509e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.55468491e-03],
       [ 6.24790298e-01,  2.82513509e-03,  1.91107639e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.60567578e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.05000000e+02, -7.04398054e-01,  1.20474096e-01,
         1.13287411e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.04398054e-01,  1.01917668e-02, -8.19610043e-05,
        -2.80966113e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.20474096e-01, -8.19610043e-05,  7.91675532e-03,
        -9.85884084e-04]])

In [20]:
# credit to https://www.geeksforgeeks.org/dsa/gaussian-elimination/
def gaussianElimination(mat, N=3):
    for k in range(N):
        i_max = max(range(k, N), key=lambda i: abs(mat[i][k]))
        if mat[i_max][k] == 0:
            print("Singular Matrix.")
            print("Inconsistent System." if mat[i_max][N]
                  else "May have infinitely many solutions.")
            return
        mat[k], mat[i_max] = mat[i_max], mat[k]

        for i in range(k + 1, N):
            f = mat[i][k] / mat[k][k]
            mat[i][k + 1:] = [mat[i][j] - f * mat[k][j]
                              for j in range(k + 1, N + 1)]
            mat[i][k] = 0

    x = [0] * N
    for i in range(N - 1, -1, -1):
        x[i] = (mat[i][N] - sum(mat[i][j] * x[j]
                for j in range(i + 1, N))) / mat[i][i]

    print("\nSolution for the system:")
    for xi in x:
        print(f"{xi:.8f}")

    return np.array(x)

In [21]:
normal_soln = gaussianElimination(normal_system, N=normal_system.shape[0])


Solution for the system:
0.00151337
0.17215290
0.16607285
-0.00121269
-0.36037682
-0.10980804


In [22]:
np.linalg.norm(A @ normal_soln - b)

0.15297704991440925

### iii.b Perhitungan Condition Number

In [23]:
np.linalg.cond(A)

192.60541021575767

In [24]:
np.linalg.cond(A_normal)

37096.84404438027

### iii.c Analisis pengaruh condition Number

In [25]:
b_perturbed = b + np.random.normal(0, 0.1, size=b.size)

In [26]:
b_diff = abs(b - b_perturbed)

In [27]:
print(f"mean perturbation: {b_diff.mean()}")
print(f"max perturbation: {b_diff.max()}")

mean perturbation: 0.08177699612940648
max perturbation: 0.2829480312052178


In [28]:
b_pert_normal = A.T @ b_perturbed

In [29]:
perturbed_normal_system = np.concatenate((A_normal, b_pert_normal.reshape(-1, 1)), axis=1)

In [30]:
perturbed_normal_soln = gaussianElimination(perturbed_normal_system, N=normal_system.shape[0])


Solution for the system:
0.01065396
-0.54784499
0.31958223
0.00760061
0.49533190
-0.90324858


In [31]:
normal_diff = abs(perturbed_normal_soln - normal_soln)

In [32]:
print(f"mean perturbation: {normal_diff.mean()}")
print(f"max perturbation: {normal_diff.max()}")

mean perturbation: 0.4234350700987039
max perturbation: 0.8557087263946916


In [33]:
def givens(mat):
    Q = np.eye(mat.shape[0])
    for i in range(mat.shape[1]):
        for j in range(i+1, mat.shape[0]):
            if mat[j, i] == 0: continue

            G = np.eye(mat.shape[0])
            alpha = np.sqrt(mat[j, i]**2 + mat[i, i]**2)
            s = mat[j, i]/alpha
            c= mat[i, i]/alpha
            G[i, i] = c
            G[j, j] = c
            G[i, j] = s
            G[j, i] = -s

            # Verifikasi algoritma, menjawab (iv.c)

            print(f"G_k untuk mengeliminasi elemen {(j+1, i+1)}:\n" + str(G))

            mat = G @ mat
            Q = G @ Q

            print("Hasil G_k @ A:\n" + str(mat))

            print(f"Apakah elemen {(j+1, i+1)} (mendekati) 0: " + str(abs(mat[j, i]) < 1e-9) +"\n\n\n")


    return Q, mat

In [34]:
test = np.linspace(1, 12, 12).reshape(4, 3)

In [35]:
test

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [36]:
givens(test)

G_k untuk mengeliminasi elemen (2, 1):
[[ 0.24253563  0.9701425   0.          0.        ]
 [-0.9701425   0.24253563  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Hasil G_k @ A:
[[ 4.12310563  5.33578375  6.54846188]
 [ 0.         -0.72760688 -1.45521375]
 [ 7.          8.          9.        ]
 [10.         11.         12.        ]]
Apakah elemen (2, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (3, 1):
[[ 0.50751922  0.          0.86164044  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.86164044  0.          0.50751922  0.        ]
 [ 0.          0.          0.          1.        ]]
Hasil G_k @ A:
[[ 8.12403840e+00  9.60113630e+00  1.10782342e+01]
 [ 0.00000000e+00 -7.27606875e-01 -1.45521375e+00]
 [-3.33066907e-16 -5.37373291e-01 -1.07474658e+00]
 [ 1.00000000e+01  1.10000000e+01  1.20000000e+01]]
Apakah elemen (3, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (

(array([[ 0.07761505,  0.31046021,  0.54330537,  0.77615053],
        [ 0.83305216,  0.45123659,  0.06942101, -0.31239456],
        [-0.38807446,  0.22933712,  0.70554913, -0.54681179],
        [-0.38652066,  0.80461449, -0.44966702,  0.03157318]]),
 array([[ 1.28840987e+01,  1.45916299e+01,  1.62991610e+01],
        [ 6.18716241e-17,  1.04131520e+00,  2.08263040e+00],
        [-2.74982398e-16,  3.25648366e-18,  9.69299876e-16],
        [ 2.84242774e-16,  2.77958970e-17, -5.97829486e-33]]))

### iv.b Penyelesaian Metode QR Givens Rotation

In [37]:
Q, R = givens(A)

G_k untuk mengeliminasi elemen (2, 1):
[[ 0.  1.  0. ...  0.  0.  0.]
 [-1.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
Hasil G_k @ A:
[[ 1.          0.00737754 -0.00831972  0.          0.          0.        ]
 [ 0.          0.          0.         -1.          0.00831972 -0.002438  ]
 [ 0.          0.          0.          1.         -0.01309625  0.00737754]
 ...
 [ 0.          0.          0.          1.         -0.00843476 -0.00488232]
 [ 1.          0.01775331 -0.00843476  0.          0.          0.        ]
 [ 0.          0.          0.          1.         -0.00160533  0.01775331]]
Apakah elemen (2, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (4, 1):
[[0.70710678 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.      

Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.27846504e-17  9.96645910e-20  5.32604091e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (27, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (30, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99848097 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0. 

In [38]:
Q.shape, R.shape

((300, 300), (300, 6))

In [39]:
b.shape

(300,)

In [40]:
d = Q @ b

In [41]:
d_hat = d[:A.shape[1]]

In [42]:
d_hat

array([ 0.04638535,  0.00962568,  0.02138096,  0.01105572, -0.02772282,
       -0.00962437])

In [43]:
R_hat = R[:A.shape[1]]

In [44]:
R_hat

array([[ 1.39642400e+01,  1.03522935e-01,  4.47421625e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09685097e-17,  7.82009438e-02, -2.31033643e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.61687088e-17,  4.16129287e-19,  1.28744466e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.02469508e+01, -6.87422112e-02,  1.17570679e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.80904835e-17,  7.39342629e-02,  9.82285904e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.35774769e-18,  2.20701130e-19,  8.76472368e-02]])

In [45]:
givens_system = np.concatenate((R_hat, d_hat.reshape(-1, 1)), axis=1)

In [46]:
def back_subtitution(mat, N=3):
    # for k in range(N):
    #     i_max = max(range(k, N), key=lambda i: abs(mat[i][k]))
    #     if mat[i_max][k] == 0:
    #         print("Singular Matrix.")
    #         print("Inconsistent System." if mat[i_max][N]
    #               else "May have infinitely many solutions.")
    #         return
    #     mat[k], mat[i_max] = mat[i_max], mat[k]

    #     for i in range(k + 1, N):
    #         f = mat[i][k] / mat[k][k]
    #         mat[i][k + 1:] = [mat[i][j] - f * mat[k][j]
    #                           for j in range(k + 1, N + 1)]
    #         mat[i][k] = 0

    x = [0] * N
    for i in range(N - 1, -1, -1):
        x[i] = (mat[i][N] - sum(mat[i][j] * x[j]
                for j in range(i + 1, N))) / mat[i][i]

    print("\nSolution for the system:")
    for xi in x:
        print(f"{xi:.8f}")

    return np.array(x)

In [47]:
givens_soln = back_subtitution(givens_system, A.shape[1])


Solution for the system:
0.00151337
0.17215290
0.16607285
-0.00121269
-0.36037682
-0.10980804


In [48]:
np.linalg.norm(A @ givens_soln - b)

0.15297704991440925